### PR TITLE
fix(canvas-CanvasContainer):  修改Model单词拼写错误

### PR DESCRIPTION
**Pull request by jxhhdx**
English | [简体中文](https://github.com/opentiny/tiny-engine/blob/develop/.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.zh-CN.md)

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-engine/blob/develop/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Built its own designer, fully self-validated

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

### What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by chilingling** [comment]
@jxhhdx 麻烦描述清楚修改的相关背景，是什么原因需要修改，为什么这样修改。

**Comment by chilingling** [comment]
当前看是修改了一个单词拼写错误？

**Comment by jxhhdx** [comment]
> 当前看是修改了一个单词拼写错误？

是的

**Comment by chilingling** [comment]
> > 当前看是修改了一个单词拼写错误？
> 
> 是的

好的，感谢贡献

**Review by chilingling — APPROVED** [review]

**Pull request merged**
